version: '3'

services:
  app:
    image: microsoft/dotnet:2.2-sdk
    volumes:
      - ./app:/app/
      - ./docker/secrets/appsettings.json:/app/appsettings.json
    working_dir: /app/
    command: dotnet watch run
    ports:
      - "8080:5000"
    depends_on:
      - db
