version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: not_for_production_use
  app:
    image: startupideas-django:latest
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
